on: [push]
jobs:
  deploy-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Sevalla Deploy
        uses: sevalla-hosting/sevalla-deploy@v1.0.1
        with:
          action: deploy-static-site
          sevalla-token: ${{ secrets.SEVALLA_TOKEN }}
          static-site-id: ${{ secrets.STATIC_SITE_ID }}
          branch: main
          wait-for-finish: true
