name: Deploy ghall.space
run-name: ${{ github.actor }} is deploying static website
on: [push]
jobs:
  deploy-static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: sevalla-hosting/sevalla-deploy@v1.0.0
        with:
          action: deploy-static-site
          sevalla-token: ${{ secrets.SEVALLA_TOKEN }}
          static-site-id: ${{ secrets.STATIC_SITE_ID }}
          branch: main
          wait-for-finish: true
